// Generated by CodiumAI
import {dayOfYear} from '../src/worldtime-api/src/worldtime.ts'
describe('dayOfYear', () => {

    // Returns the correct day of the year for a valid input date.
    it('should return the correct day of the year when a valid input date is provided', () => {
      const date = new Date(2022, 0, 1);
      const result = dayOfYear(date);
      expect(result).toBe(1);
    });

    // Returns NaN for an invalid input date.
    it('should return NaN when an invalid input date is provided', () => {
      const date = new Date('invalid');
      const result = dayOfYear(date);
      expect(result).toBe(NaN);
    });
});
